#!/bin/bash
set -e

echo "=== LaboratorioAI - Init PostgreSQL ==="

# Crear base de datos n8n_db
echo "Creando n8n_db..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE DATABASE n8n_db;" 2>/dev/null || echo "  n8n_db ya existe"

# Extensiones y usuario
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
    CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
    ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_NON_ROOT_USER};
    CREATE SCHEMA IF NOT EXISTS n8n;
    CREATE SCHEMA IF NOT EXISTS floowise;
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
    GRANT ALL PRIVILEGES ON DATABASE n8n_db TO ${POSTGRES_NON_ROOT_USER};
    GRANT ALL PRIVILEGES ON SCHEMA n8n TO ${POSTGRES_NON_ROOT_USER};
    GRANT ALL PRIVILEGES ON SCHEMA floowise TO ${POSTGRES_NON_ROOT_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
    GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
EOSQL

echo "=== Init completado ==="
